### ISSUE TITLE
HTTPError: 400 Client Error: Bad Request for url: https://avatar.lyrebird.ai/api/v0/generate

### ISSUE THREAD

**Issue by kest-dev** [MartinHowarth/lyrebot#5]
I don't know if this is a known issue or I'm just doing something wrong. But I get this error every time I try to make this bot use the API. It prints out this:

> 2019-07-06 07:56:53,377 - discord_bot - ERROR - command_error: <discord.ext.commands.context.Context object at 0x0000021EF61CF4A8>; Command raised an exception: HTTPError: 400 Client Error: Bad Request for url: https://avatar.lyrebird.ai/api/v0/generate
> Ignoring exception in command speak:
> Traceback (most recent call last):
>   File "C:\Users\Meow\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\ext\commands\core.py", line 63, in wrapped
>     ret = await coro(*args, **kwargs)
>   File "D:\Desktop\lyrebot-master\lyrebot\discord_bot.py", line 162, in speak
>     await self.speak_aloud(ctx.message, *words)
>   File "D:\Desktop\lyrebot-master\lyrebot\discord_bot.py", line 135, in speak_aloud
>     sentence, self.lyrebird_tokens[ident])
>   File "D:\Desktop\lyrebot-master\lyrebot\lyrebird.py", line 72, in generate_voice_for_text
>     result.raise_for_status()
>   File "C:\Users\Meow\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\models.py", line 940, in raise_for_status
>     raise HTTPError(http_error_msg, response=self)
> requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://avatar.lyrebird.ai/api/v0/generate
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "C:\Users\Meow\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\ext\commands\bot.py", line 860, in invoke
>     await ctx.command.invoke(ctx)
>   File "C:\Users\Meow\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\ext\commands\core.py", line 698, in invoke
>     await injected(*ctx.args, **ctx.kwargs)
>   File "C:\Users\Meow\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\ext\commands\core.py", line 72, in wrapped
>     raise CommandInvokeError(exc) from exc
> discord.ext.commands.errors.CommandInvokeError: Command raised an exception: HTTPError: 400 Client Error: Bad Request for url: https://avatar.lyrebird.ai/api/v0/generate

I don't know if I'm doing something wrong or what. But for whatever reason, I can't get it to speak.

**Comment by MartinHowarth** [comment]
Hi, thanks for reporting this!

Best guess is that you've included an illegal character in the Auth token, resulting in an invalid http call.

Can you try this curl request (using your token) please:
```
curl -H 'Content-Type: application/json'
-H 'Authorization: Bearer 18QdNlaDvkzMbgQ5SXmKNGmexWo'
'https://avatar.lyrebird.ai/api/v0/generate' -d
'{
    "text": "Hello World"
}'
```


Otherwise, maybe it's a Windows Vs Linux problem - I've only tested this bot on Linux. I'll investigate further when I'm back on a PC later today :)

**Comment by kest-dev** [comment]
Sorry for such a late reply. I did find a way to do it, but it requires going to the local storage of the recordings with the developer console on the website. There, you'll find a token of the recordings. That's the code you need apparently. It's probably windows as well, but hopefully, there's a fix for this.

Edit: I was not having an issue with generating the token via bot. But it was just the bot not giving me something usable for me to insert. Instead it gave me something like "oauth_[Some code]".

**Comment by MartinHowarth** [comment]
"oauth_[Some code]" is the auth token to set in the bot. I'll update the help text to make it clear that it's expected to take that format.
