### ISSUE TITLE
NoneType error

### ISSUE THREAD

**Issue by stijnb1234** [MartinHowarth/lyrebot#6]
I'm getting this error:

```
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Stijn\Anaconda3\lib\site-packages\discord.py-1.2.3-py3.7.egg\discord\client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Stijn\Anaconda3\lib\site-packages\lyrebot-0.1.0-py3.7.egg\lyrebot\discord_bot.py", line 189, in on_message
    message.author.voice.channel is not None,
AttributeError: 'NoneType' object has no attribute 'channel'
```

How to fix that?

**Comment by MartinHowarth** [comment]
That error is probably because you are not in a voice channel in discord -
the bot joins the voice channel that you are in.

Can you try again after you've joined a voice channel and let me know if
you hit the same error.

I'll make the error message clearer- thanks for the report!
